services:
  opensearch:
    image: opensearchproject/opensearch:2.9.0
    container_name: opensearch
    environment:
      - cluster.name=opensearch-cluster
      - node.name=opensearch-node1
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - 'OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m'
      - plugins.security.disabled=true
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - opensearch-data:/usr/share/opensearch/data
    ports:
      - '9200:9200'
      - '9600:9600'
    restart: unless-stopped
    healthcheck:
      test:
        [
          'CMD-SHELL',
          'curl -sS http://localhost:9200/ >/dev/null 2>&1 || exit 1',
        ]
      interval: 10s
      timeout: 5s
      retries: 12

  minio:
    image: minio/minio:latest
    container_name: minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    ports:
      - '9000:9000'
      - '9001:9001'
    volumes:
      - minio-data:/data
    restart: unless-stopped
    healthcheck:
      test:
        [
          'CMD-SHELL',
          'curl -f http://localhost:9000/minio/health/ready || exit 1',
        ]
      interval: 10s
      timeout: 5s
      retries: 12

volumes:
  opensearch-data:
    driver: local
  minio-data:
    driver: local
